version: '3.7'

services:
  golang-dev:
    image: golang:bullseye
    container_name: golang-dev
    stdin_open: true
    tty: true
    working_dir: /go/src
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      # docker in docker
      - /var/run/docker.sock:/var/run/docker.sock 
      - ./code/go:/go
      - ./init.sh:/tmp/init.sh
    deploy:
      resources:
        limits:
          memory: 2G
    # command: ["bash", "/tmp/init.sh", "golang"]

  #  Databases 
  redis:
    image: redis:alpine
    container_name: redis

# networks:
#   backend:
#     driver: bridge
#   frontend:
#     driver: bridge