version: '3'

services:
  etcd:
    image: bitnami/etcd:latest # https://github.com/bitnami/bitnami-docker-etcd
    container_name: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      # - ETCD_ROOT_PASSWORD=!passwd
      # - ETCD_INIT_SNAPSHOTS_DIR
      # - ETCD_CLUSTER_DOMAIN
      # - ETCD_START_FROM_SNAPSHOT
      # - ETCD_DISASTER_RECOVERY
      # - ETCD_ON_K8S
      # - ETCD_INIT_SNAPSHOT_FILENAME
      # - ETCDCTL_API
      # - ETCD_LOG_LEVEL
      # - ETCD_LISTEN_CLIENT_URLS
      # - ETCD_ADVERTISE_CLIENT_URLS
      # - ETCD_INITIAL_CLUSTER
      # - ETCD_INITIAL_CLUSTER_STATE
      # - ETCD_LISTEN_PEER_URLS
      # - ETCD_INITIAL_ADVERTISE_PEER_URLS
      # - ETCD_INITIAL_CLUSTER_TOKEN
      # - ETCD_AUTO_TLS
      # - ETCD_CERT_FILE
      # - ETCD_KEY_FILE
      # - ETCD_TRUSTED_CA_FILE
      # - ETCD_CLIENT_CERT_AUTH
      # - ETCD_PEER_AUTO_TLS
    ports:
      - 2379:2379
      - 2380:2380
    # volumes:
    #   - ./etcd/conf/etcd.conf.yml:/opt/bitnami/etcd/conf/etcd.conf.yml
  e3w:
    hostname: e3w
    image: soyking/e3w:latest
    container_name: e3w
    ports:
      - "12379:8080"
    volumes:
      - "./e3w/conf/config.ini:/app/conf/config.default.ini"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data

  postgre:
    image: postgres:13.6-alpine
    container_name: postgre
    ports:
      - 5432:5432
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      # POSTGRES_USER:
      # POSTGRES_PASSWORD: example
    volumes:
      - ./postgre/data:/var/lib/postgresql/data/
  adminer:  # adminer
    image: adminer
    container_name: adminer
    ports:
      - 15432:15432

networks:
  db-net:
    driver: bridge
  e3wnet:
    name: e3wnet
  app-net:
    external: true
    name: app-net