version: '3.7'

services:
  etcd:
    hostname: etcd
    image: bitnami/etcd:latest # https://github.com/bitnami/bitnami-docker-etcd
    container_name: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      # - ETCD_ROOT_PASSWORD=!passwd
      # - ETCD_INIT_SNAPSHOTS_DIR
      # - ETCD_CLUSTER_DOMAIN
      # - ETCD_START_FROM_SNAPSHOT
      # - ETCD_DISASTER_RECOVERY
      # - ETCD_ON_K8S
      # - ETCD_INIT_SNAPSHOT_FILENAME
      # - ETCDCTL_API
      # - ETCD_LOG_LEVEL
      # - ETCD_LISTEN_CLIENT_URLS
      # - ETCD_ADVERTISE_CLIENT_URLS
      # - ETCD_INITIAL_CLUSTER
      # - ETCD_INITIAL_CLUSTER_STATE
      # - ETCD_LISTEN_PEER_URLS
      # - ETCD_INITIAL_ADVERTISE_PEER_URLS
      # - ETCD_INITIAL_CLUSTER_TOKEN
      # - ETCD_AUTO_TLS
      # - ETCD_CERT_FILE
      # - ETCD_KEY_FILE
      # - ETCD_TRUSTED_CA_FILE
      # - ETCD_CLIENT_CERT_AUTH
      # - ETCD_PEER_AUTO_TLS
    ports:
      - 2379:2379
      - 2380:2380
    # volumes:
    #   - ./etcd/conf/etcd.conf.yml:/opt/bitnami/etcd/conf/etcd.conf.yml
  e3w:
    hostname: e3w
    image: soyking/e3w:latest
    container_name: e3w
    ports:
      - "12379:8080"
    volumes:
      - "./e3w/conf/config.ini:/app/conf/config.default.ini"

  redis:
    hostname: etcd
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data

  postgre:
    hostname: postgre
    image: postgres:13.6-alpine
    container_name: postgre
    ports:
      - 5432:5432
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      # POSTGRES_USER:
      # POSTGRES_PASSWORD: example
    volumes:
      - ./postgre/data:/var/lib/postgresql/data/
  adminer:  # adminer
    image: adminer
    container_name: adminer
    ports:
      - 15432:15432

  kafka:
    image: bitnami:kafka
    container_name: kafka
    ports:
      - "9092:9092"
  mysql:
    hostname: mysql
    image: mysql:latest # 8.0.27
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      # pwgen -ysncC 10 生成
      - MYSQL_ROOT_PASSWORD=9xM3@RXl0m
      # This variable is optional and allows you to specify the name of a database to be created on image startup. If a user/password was supplied (see below) then that user will be granted superuser access (corresponding to GRANT ALL) to this database.
      # These variables are optional, used in conjunction to create a new user and to set that user's password. This user will be granted superuser permissions (see above) for the database specified by the MYSQL_DATABASE variable. Both variables are required for a user to be created.Do note that there is no need to use this mechanism to create the root superuser, that user gets created by default with the password specified by the MYSQL_ROOT_PASSWORD variable.
      # - MYSQL_DATABASE: 
      # - MYSQL_USER: 
      # - MYSQL_PASSWORD:

      # This is an optional variable. Set to a non-empty value, like yes, to allow the container to be started with a blank password for the root user. NOTE: Setting this variable to yes is not recommended unless you really know what you are doing, since this will leave your MySQL instance completely unprotected, allowing anyone to gain complete superuser access.
      # - MYSQL_ALLOW_EMPTY_PASSWORD: yes

      # This is an optional variable. Set to a non-empty value, like yes, to generate a random initial password for the root user (using pwgen). The generated root password will be printed to stdout (GENERATED ROOT PASSWORD: .....).
      # - MYSQL_RANDOM_ROOT_PASSWORD: yes
      # - MYSQL_ONETIME_PASSWORD:
      # Sets root (not the user specified in MYSQL_USER!) user as expired once init is complete, forcing a password change on first login. Any non-empty value will activate this setting. NOTE: This feature is supported on MySQL 5.6+ only. Using this option on MySQL 5.5 will throw an appropriate error during initialization.
    volumes:
      - ./mysql/data:/var/lib/mysql

networks:
  db-net:
    driver: bridge
  e3wnet:
    name: e3wnet
  app-net:
    external: true
    name: app-net